### ISSUE TITLE
感觉 ini 配置文件会更简洁一些

### ISSUE THREAD

**Issue by yoonper** [TheWinds/devgo#1]
[groupName]
itemName=itemValue

**Comment by TheWinds** [comment]
ini比较简洁，但是ini是一维的

**Comment by yoonper** [comment]
Config 的等效配置：
```
[tools]
hello=echo hello devgo
date now=date

[website]
github=open https://github.com

[devgo]
edit config=vim $HOME/.devgo
```

还是说 devgo 有其他特性在 README.md 中没有体现？

**Comment by TheWinds** [comment]
> Config 的等效配置：
> 
> ```
> [tools]
> hello=echo hello devgo
> date now=date
> 
> [website]
> github=open https://github.com
> 
> [devgo]
> edit config=vim $HOME/.devgo
> ```
> 
> 还是说 devgo 有其他特性在 README.md 中没有体现？

是的这样更简洁，但是要想加其他字段的话就比较麻烦了，目前有支持 yaml 的PR，暂时不考虑支持ini了
